"""add investigation tasks

Revision ID: 9e261a00f295
Revises: c91e8f2a6d44
Create Date: 2026-07-21 14:47:25.661424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e261a00f295'
down_revision: Union[str, Sequence[str], None] = 'c91e8f2a6d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigation_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('priority', sa.String(length=20), server_default='medium', nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_username', sa.String(length=100), nullable=False),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_username', sa.String(length=100), nullable=True),
    sa.Column('completed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('completed_by_username', sa.String(length=100), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_note', sa.Text(), nullable=True),
    sa.Column('cancelled_by_user_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_by_username', sa.String(length=100), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_username', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['fraud_case_reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_tasks_assigned_to_user_id'), 'investigation_tasks', ['assigned_to_user_id'], unique=False)
    op.create_index('ix_investigation_tasks_assignee_status', 'investigation_tasks', ['assigned_to_user_id', 'status'], unique=False)
    op.create_index('ix_investigation_tasks_case_created_at', 'investigation_tasks', ['case_id', 'created_at'], unique=False)
    op.create_index('ix_investigation_tasks_case_deleted', 'investigation_tasks', ['case_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_investigation_tasks_case_id'), 'investigation_tasks', ['case_id'], unique=False)
    op.create_index('ix_investigation_tasks_case_status', 'investigation_tasks', ['case_id', 'status'], unique=False)
    op.create_index(op.f('ix_investigation_tasks_created_at'), 'investigation_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_investigation_tasks_created_by_user_id'), 'investigation_tasks', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_investigation_tasks_due_at'), 'investigation_tasks', ['due_at'], unique=False)
    op.create_index('ix_investigation_tasks_due_status', 'investigation_tasks', ['due_at', 'status'], unique=False)
    op.create_index(op.f('ix_investigation_tasks_is_deleted'), 'investigation_tasks', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_investigation_tasks_priority'), 'investigation_tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_investigation_tasks_status'), 'investigation_tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigation_tasks_status'), table_name='investigation_tasks')
    op.drop_index(op.f('ix_investigation_tasks_priority'), table_name='investigation_tasks')
    op.drop_index(op.f('ix_investigation_tasks_is_deleted'), table_name='investigation_tasks')
    op.drop_index('ix_investigation_tasks_due_status', table_name='investigation_tasks')
    op.drop_index(op.f('ix_investigation_tasks_due_at'), table_name='investigation_tasks')
    op.drop_index(op.f('ix_investigation_tasks_created_by_user_id'), table_name='investigation_tasks')
    op.drop_index(op.f('ix_investigation_tasks_created_at'), table_name='investigation_tasks')
    op.drop_index('ix_investigation_tasks_case_status', table_name='investigation_tasks')
    op.drop_index(op.f('ix_investigation_tasks_case_id'), table_name='investigation_tasks')
    op.drop_index('ix_investigation_tasks_case_deleted', table_name='investigation_tasks')
    op.drop_index('ix_investigation_tasks_case_created_at', table_name='investigation_tasks')
    op.drop_index('ix_investigation_tasks_assignee_status', table_name='investigation_tasks')
    op.drop_index(op.f('ix_investigation_tasks_assigned_to_user_id'), table_name='investigation_tasks')
    op.drop_table('investigation_tasks')
    # ### end Alembic commands ###
