"""Add fraud case comments

Revision ID: b556c590b845
Revises: 3b7d8e9f1a2c
Create Date: 2026-07-20 14:32:45.283374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b556c590b845'
down_revision: Union[str, Sequence[str], None] = '3b7d8e9f1a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.Column('author_username', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=30), server_default='internal', nullable=False),
    sa.Column('is_edited', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('deleted_by_username', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['fraud_case_reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_comments_author_user_id'), 'case_comments', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_case_comments_author_username'), 'case_comments', ['author_username'], unique=False)
    op.create_index('ix_case_comments_case_created_at', 'case_comments', ['case_id', 'created_at'], unique=False)
    op.create_index('ix_case_comments_case_deleted', 'case_comments', ['case_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_case_comments_case_id'), 'case_comments', ['case_id'], unique=False)
    op.create_index('ix_case_comments_case_visibility', 'case_comments', ['case_id', 'visibility'], unique=False)
    op.create_index(op.f('ix_case_comments_created_at'), 'case_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_case_comments_is_deleted'), 'case_comments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_case_comments_visibility'), 'case_comments', ['visibility'], unique=False)
    op.create_table('case_comment_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('editor_user_id', sa.Integer(), nullable=True),
    sa.Column('editor_username', sa.String(length=100), nullable=False),
    sa.Column('previous_content', sa.Text(), nullable=False),
    sa.Column('previous_visibility', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['case_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['editor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_case_comment_revisions_comment_created_at', 'case_comment_revisions', ['comment_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_case_comment_revisions_comment_id'), 'case_comment_revisions', ['comment_id'], unique=False)
    op.create_index(op.f('ix_case_comment_revisions_created_at'), 'case_comment_revisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_case_comment_revisions_editor_user_id'), 'case_comment_revisions', ['editor_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_comment_revisions_editor_user_id'), table_name='case_comment_revisions')
    op.drop_index(op.f('ix_case_comment_revisions_created_at'), table_name='case_comment_revisions')
    op.drop_index(op.f('ix_case_comment_revisions_comment_id'), table_name='case_comment_revisions')
    op.drop_index('ix_case_comment_revisions_comment_created_at', table_name='case_comment_revisions')
    op.drop_table('case_comment_revisions')
    op.drop_index(op.f('ix_case_comments_visibility'), table_name='case_comments')
    op.drop_index(op.f('ix_case_comments_is_deleted'), table_name='case_comments')
    op.drop_index(op.f('ix_case_comments_created_at'), table_name='case_comments')
    op.drop_index('ix_case_comments_case_visibility', table_name='case_comments')
    op.drop_index(op.f('ix_case_comments_case_id'), table_name='case_comments')
    op.drop_index('ix_case_comments_case_deleted', table_name='case_comments')
    op.drop_index('ix_case_comments_case_created_at', table_name='case_comments')
    op.drop_index(op.f('ix_case_comments_author_username'), table_name='case_comments')
    op.drop_index(op.f('ix_case_comments_author_user_id'), table_name='case_comments')
    op.drop_table('case_comments')
    # ### end Alembic commands ###
